name: Build Docker image

on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    build-docker-image:
        runs-on: ubuntu-latest
        env:
            PLATFORMS: linux/amd64
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.CR_PAT }}
            -   name: Build and push dev-master
                uses: docker/build-push-action@v2
                with:
                    push: true
                    platforms: ${{ env.PLATFORMS }}
                    build-args: |
                        TYPO3_RECTOR_VERSION=dev-master
                        TYPO3_RECTOR_VERSION_HASH=${{ github.sha }}
                    tags: |
                        schreiberten/typo3-rector:dev-master
                        ghcr.io/sabbelasichon/typo3-rector:dev-master
            -   name: Get the version
                if: startsWith(github.ref, 'refs/tags/v')
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
            -   name: Build and push latest
                uses: docker/build-push-action@v2
                if: startsWith(github.ref, 'refs/tags/v')
                with:
                    push: true
                    platforms: ${{ env.PLATFORMS }}
                    build-args: |
                        TYPO3_RECTOR_VERSION=${{ steps.get_version.outputs.VERSION }}
                        TYPO3_RECTOR_VERSION_HASH=${{ github.sha }}
                    tags: |
                        schreiberten/typo3-rector
                        schreiberten/typo3-rector:${{ steps.get_version.outputs.VERSION }}
                        ghcr.io/sabbelasichon/typo3-rector
                        ghcr.io/sabbelasichon/typo3-rector:${{ steps.get_version.outputs.VERSION }}
