name: Docs

on:
    push:
        branches:
            - master

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none
            -   run: composer install --no-progress

            -   name: Generate documentation
                run: composer docs

            -   uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Generate documentation
                    commit_options: '--no-verify --signoff'
                    branch: "master"
                    push_options: '--force'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
